### ISSUE TITLE
RTNETLINK answers: Operation not supported

### ISSUE THREAD

**Issue by ConnorRigby** [nerves-networking/vintage_net#41]
I think this just means i am missing a package, but i can't figure out which one it is. 
```
17:17:31.298 module=gen_server [error] GenServer VintageNet.RouteManager terminating
** (MatchError) no match of right hand side value: {:error, "ip: RTNETLINK answers: Operation not supported\n"}
    (vintage_net) lib/vintage_net/route_manager.ex:238: VintageNet.RouteManager.handle_insert/1
    (elixir) lib/enum.ex:769: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:769: Enum.each/2
    (elixir) lib/enum.ex:769: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:769: Enum.each/2
    (vintage_net) lib/vintage_net/route_manager.ex:199: VintageNet.RouteManager.update_route_tables/1
    (vintage_net) lib/vintage_net/route_manager.ex:136: VintageNet.RouteManager.handle_call/3
    (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
Last message (from VintageNet.ToElixir.Server): {:set_route, "wlan0", [{{192, 168, 86, 32}, 24}], {192, 168, 86, 1}, :lan}
State: %VintageNet.RouteManager.State{interfaces: %{}, prioritization: [ethernet: :internet, wifi: :internet, mobile: :internet, _: :internet, ethernet: :lan, wifi: :lan, mobile: :lan, _: :lan], route_state: %{}, routes: []}
Client VintageNet.ToElixir.Server is alive

    (stdlib) gen.erl:169: :gen.do_call/4
    (elixir) lib/gen_server.ex:986: GenServer.call/3
    (vintage_net) lib/vintage_net/interface/udhcpc.ex:91: VintageNet.Interface.Udhcpc.renew/2
    (vintage_net) lib/vintage_net/interface/udhcpc.ex:140: VintageNet.Interface.Udhcpc.bound/2
    (vintage_net) lib/vintage_net/to_elixir/server.ex:48: VintageNet.ToElixir.Server.dispatch/1
    (vintage_net) lib/vintage_net/to_elixir/server.ex:36: VintageNet.ToElixir.Server.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
 
17:17:31.307 module=proc_lib [error] Process VintageNet.RouteManager (#PID<0.1348.0>) terminating
** (MatchError) no match of right hand side value: {:error, "ip: RTNETLINK answers: Operation not supported\n"}
    (vintage_net) lib/vintage_net/route_manager.ex:238: VintageNet.RouteManager.handle_insert/1
    (elixir) lib/enum.ex:769: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:769: Enum.each/2
    (elixir) lib/enum.ex:769: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:769: Enum.each/2
    (vintage_net) lib/vintage_net/route_manager.ex:199: VintageNet.RouteManager.update_route_tables/1
    (vintage_net) lib/vintage_net/route_manager.ex:136: VintageNet.RouteManager.handle_call/3
    (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
Initial Call: VintageNet.RouteManager.init/1
Ancestors: [VintageNet.Supervisor, #PID<0.982.0>]
Message Queue Length: 0
Messages: []
Links: [#PID<0.983.0>]
Dictionary: [] 
Trapping Exits: false
Status: :running
Heap Size: 17731
Stack Size: 27
Reductions: 29271
 
17:17:31.315 module=supervisor [error] Child VintageNet.RouteManager of Supervisor VintageNet.Supervisor terminated
** (exit) an exception was raised:
    ** (MatchError) no match of right hand side value: {:error, "ip: RTNETLINK answers: Operation not supported\n"}
        (vintage_net) lib/vintage_net/route_manager.ex:238: VintageNet.RouteManager.handle_insert/1
        (elixir) lib/enum.ex:769: Enum."-each/2-lists^foreach/1-0-"/2
        (elixir) lib/enum.ex:769: Enum.each/2
        (elixir) lib/enum.ex:769: Enum."-each/2-lists^foreach/1-0-"/2
        (elixir) lib/enum.ex:769: Enum.each/2
        (vintage_net) lib/vintage_net/route_manager.ex:199: VintageNet.RouteManager.update_route_tables/1
        (vintage_net) lib/vintage_net/route_manager.ex:136: VintageNet.RouteManager.handle_call/3
        (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
Pid: #PID<0.1348.0>
Start Call: VintageNet.RouteManager.start_link([])
Restart: :permanent
Shutdown: 5000
Type: :worker
 
17:17:31.333 module=gen_server [error] GenServer VintageNet.ToElixir.Server terminating
** (stop) exited in: GenServer.call(VintageNet.RouteManager, {:set_route, "wlan0", [{{192, 168, 86, 32}, 24}], {192, 168, 86, 1}, :lan}, 5000)
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, "ip: RTNETLINK answers: Operation not supported\n"}
            (vintage_net) lib/vintage_net/route_manager.ex:238: VintageNet.RouteManager.handle_insert/1
            (elixir) lib/enum.ex:769: Enum."-each/2-lists^foreach/1-0-"/2
            (elixir) lib/enum.ex:769: Enum.each/2
            (elixir) lib/enum.ex:769: Enum."-each/2-lists^foreach/1-0-"/2
            (elixir) lib/enum.ex:769: Enum.each/2
            (vintage_net) lib/vintage_net/route_manager.ex:199: VintageNet.RouteManager.update_route_tables/1
            (vintage_net) lib/vintage_net/route_manager.ex:136: VintageNet.RouteManager.handle_call/3
            (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
    (elixir) lib/gen_server.ex:989: GenServer.call/3
    (vintage_net) lib/vintage_net/interface/udhcpc.ex:91: VintageNet.Interface.Udhcpc.renew/2
    (vintage_net) lib/vintage_net/interface/udhcpc.ex:140: VintageNet.Interface.Udhcpc.bound/2
    (vintage_net) lib/vintage_net/to_elixir/server.ex:48: VintageNet.ToElixir.Server.dispatch/1
    (vintage_net) lib/vintage_net/to_elixir/server.ex:36: VintageNet.ToElixir.Server.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:udp, #Port<0.363>, {:unspec, ""}, 0, <<131, 104, 2, 119, 6, 117, 100, 104, 99, 112, 99, 116, 0, 0, 0, 16, 119, 7, 99, 111, 109, 109, 97, 110, 100, 119, 5, 98, 111, 117, 110, 100, 119, 9, 105, 110, 116, 101, 114, 102, 97, 99, 101, 109, 0, ...>>}
State: %{path: "/tmp/vintage_net/comms", socket: #Port<0.363>}
 
17:17:31.355 module=proc_lib [error] Process VintageNet.ToElixir.Server (#PID<0.1350.0>) terminating
** (exit) exited in: GenServer.call(VintageNet.RouteManager, {:set_route, "wlan0", [{{192, 168, 86, 32}, 24}], {192, 168, 86, 1}, :lan}, 5000)
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, "ip: RTNETLINK answers: Operation not supported\n"}
            (vintage_net) lib/vintage_net/route_manager.ex:238: VintageNet.RouteManager.handle_insert/1
            (elixir) lib/enum.ex:769: Enum."-each/2-lists^foreach/1-0-"/2
            (elixir) lib/enum.ex:769: Enum.each/2
            (elixir) lib/enum.ex:769: Enum."-each/2-lists^foreach/1-0-"/2
            (elixir) lib/enum.ex:769: Enum.each/2
            (vintage_net) lib/vintage_net/route_manager.ex:199: VintageNet.RouteManager.update_route_tables/1
            (vintage_net) lib/vintage_net/route_manager.ex:136: VintageNet.RouteManager.handle_call/3
            (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
    (elixir) lib/gen_server.ex:989: GenServer.call/3
    (vintage_net) lib/vintage_net/interface/udhcpc.ex:91: VintageNet.Interface.Udhcpc.renew/2
    (vintage_net) lib/vintage_net/interface/udhcpc.ex:140: VintageNet.Interface.Udhcpc.bound/2
    (vintage_net) lib/vintage_net/to_elixir/server.ex:48: VintageNet.ToElixir.Server.dispatch/1
    (vintage_net) lib/vintage_net/to_elixir/server.ex[ ttyUSB0: 2019-05-17 13:29:57 ]
:36: VintageNet.ToElixir.Server.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Initial Call: VintageNet.ToElixir.Server.init/1
Ancestors: [VintageNet.Supervisor, #PID<0.982.0>]
Message Queue Length: 0
Messages: []
Links: [#Port<0.363>, #PID<0.983.0>]
Dictionary: []
Trapping Exits: false
Status: :running
Heap Size: 17731
Stack Size: 27
Reductions: 23016

```

**Comment by ConnorRigby** [comment]
```elixir
%{
        type: VintageNet.Technology.WiFi,
        wifi: %{
          mode: :host,
          ssid: "configure-farmbot",
          key_mgmt: :none,
          ap_scan: 1,
          bgscan: :simple
        },
        ipv4: %{
          method: :static,
          address: "192.168.24.1",
          netmask: "255.255.255.0",
          gateway: "192.168.24.1"
        },
        dhcpd: %{
          start: "192.168.24.2",
          end: "192.168.24.20"
        }
      }
```
then:
```elixir
%{type: VintageNet.Technology.Null}
```
then:
```elixir
%{
  type: VintageNet.Technology.WiFi,
  wifi: %{
    key_mgmt: :wpa_psk,
    psk: "supersecret",
    ssid: "FarmBotHQ"
  }
}
```

**Comment by ConnorRigby** [comment]
just tried it without switching modes or anything, and i got the same issue. I must just be missing a package
